### PR TITLE
www changes point to git and update favicon

### PR DESCRIPTION
**Pull request by un1versal**
Small update to www pages to what I can access here.
- [help.php] Updated to point to Github issues
- [changelog] Update to point to Github master branch commits page
- [favicon] get rid of that washed out thing use actual favicon taken from application.

Web pages (content)  need a good cleanup and once over to bring up-to-date do you really need so many pages?

### CODE REVIEW

**Comment by Stanzilla** [comment]
_more ideas moved to here https://github.com/kvirc/kvirc-www/issues/5_

**Comment by un1versal** [comment]
Stanzilla I think best to make own issue ticket with that. What happens if this is merged and or  closed? it will be buried from view.

**Comment by Stanzilla** [comment]
Alright, done. https://github.com/kvirc/kvirc-www/issues/5

**Comment by un1versal** [comment]
anyone monitoring these repos?

**Comment by HelLViS69** [comment]
Yep, website needs a full update.
Unfortunately, the motherboard of my pc is blown and atm I can't work on it.
On that pc I also have my SSL keys

**Pull request merged**
