### PR TITLE
kvirc.de should not be used anymore, it will not work soon

### PR DESCRIPTION
**Pull request by waja**

### CODE REVIEW

**Comment by DarthGandalf** [comment]
What's happening to it?

**Comment by waja** [comment]
> What's happening to it?

After so many years I'll stop providing support. I'm not using any graphical irc client since more than one decade and there are too many side projects, which needs to be reduce to get real life done.

**Comment by waja** [comment]
FYI:
```
$ host www.kvirc.de
Host www.kvirc.de not found: 3(NXDOMAIN)
```

**Comment by DarthGandalf** [comment]
I see, thanks for supporting it so far.

I don't know, is there any email accounts on this domain? If so, do they also need to move?

**Comment by waja** [comment]
> I don't know, is there any email accounts on this domain? If so, do they also need to move?

no one coupled to the project.

**Pull request merged**
