### PR TITLE
Bypass translation nightmare for Git and Snapshots pages

### PR DESCRIPTION
**Pull request by un1versal**
These two pages for now will link straight to Github wiki page
This is a simple and easy to revert change

http://www.kvirc.net/?id=snapshots
http://www.kvirc.net/?id=git

@DarthGandalf avoids the extremely unpleasant exchange in IRC 

Also solves the issue of maintenance of outdated and pages and helps simplify website maitenace.

If this works in due time expect a cleanup of the redundant code/files

### CODE REVIEW

**Comment by DarthGandalf** [comment]
+1

**Comment by un1versal** [comment]
@pragmaware its your decision here.

**Comment by un1versal** [comment]
Why instead of all that nonsense don't we add google translator to website and have it available in a gazillion languages, most of them undecipherable translations :D but all of them complete and improving all the time?

**Comment by un1versal** [comment]
Waiting for pragma is like waiting for the lottery draw where all my 6 numbers come up.

**Pull request merged**
